version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: stockapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockapp_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stockapp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    image: node:18-alpine
    container_name: stockapp-backend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: stockapp_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Если вы собираетесь использовать Marketstack API:
      # MARKETSTACK_KEY: ваш_api_key_здесь
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

volumes:
  pg_data:
